Remove android.software.connectionservice by default.
We prefer to use Tablet for SDK, no need to connectionservice.

Error:
java.lang.AssertionError: Should have at least one packages to handle Intent { act=android.intent.action.DIAL }, found []

Test: GtsGmscoreHostTestCases
com.google.android.gts.devicepolicy.managedprovisioning.DeviceOwnerProvisioningHostsideTest#testRequiredAppsInManagedUser

Signed-off-by: Bian Jin chen <kenjc.bian@rock-chips.com>
Change-Id: I4544c17e943ea728a2ebeff002b31cc2f576401d